name: Dicaeosyne
version: '${project.version}'
main: org.nemo.dicaeosyne.Dicaeosyne
api-version: '1.18'
commands:
  login:
    description: Dicaeosyne login system command for authorization.
    usage: /login [password]